# Generated by Django 3.2.11 on 2022-02-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
